version: "3.8"

services:
  redis:
    image: redis:alpine3.17
    container_name: redis
    ports:
      - 6379:6379

  app:
    build: ./app
    container_name: showIPHostapp
    ports:
      - 5000:5000
    volumes:
      - volgz:/app
#    depends_on:
#      - redis

volumes:
  volgz: